language: generic
sudo: required
cache:
  timeout: 600
  directories:
    - $TRAVIS_BUILD_DIR/target/debug
    - /opt/.cargo/git
    - /opt/.cargo/registry
services:
  - docker
git:
  depth: 1
stages:
  - CheckShell
  - Release
  - IntegrateTest
before_install:
  - docker pull cita/cita-build:ubuntu-18.04-20200606
jobs:
  include:

    - stage: CheckShell
      if: tag IS NOT present
      script:
        # Fail if any of these files have warnings
        - shellcheck scripts/*.sh env.sh

    - stage: Release
      name: Release for Integrate Test
      language: node_js
      node_js:
        # - lts/*
          - 8.10.0
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/target/release-cache
      env: HASH_ALGO=sha3hash    CRYPTO_ALGO=secp256k1
      before_script:
        - cd $TRAVIS_BUILD_DIR
        - ./scripts/replace_default_feature.sh ./ sha3hash  ${HASH_ALGO}
        - ./scripts/replace_default_feature.sh ./ secp256k1 ${CRYPTO_ALGO}
      script: ./env.sh make release
      before_cache:
        - cd $TRAVIS_BUILD_DIR
        - echo "ls old " "$(ls)"
        - cp -r  target/install docker/release/cita_secp256k1_sha3
        - echo "ls docker release is " "$(ls)"
        - rm -rf target/release-cache
        - mv -vf target/install target/release-cache

    - &stage-contract-test-sha3-secp256k1
      stage: IntegrateTest
      name: Unit Group
      if: tag IS NOT present
      language: node_js
      node_js:
        # - lts/*
          - 8.10.0
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/target/release-cache
      env: HASH_ALGO=sha3hash    CRYPTO_ALGO=secp256k1
      before_install:
        - cd $TRAVIS_BUILD_DIR
        - rm -rf target/install
        - cp -rv target/release-cache target/install
      install:
        - rm -rf /opt/cita-run/test-chain
        - cd $TRAVIS_BUILD_DIR/target/install
        - ./bin/cita create
            --nodes "127.0.0.1:4100"
            --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523"
        - ./bin/cita setup test-chain/0
        - ./bin/cita start test-chain/0
      before_script:
        - cd $TRAVIS_BUILD_DIR/target/install/scripts/contracts/tests
        - travis_retry yarn install
      script: npm run-script unit_group
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Permission
      if: tag IS NOT present
      script: npm run-script unit_permission
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Auth
      if: tag IS NOT present
      script: npm run-script unit_auth
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Chain
      if: tag IS NOT present
      script: npm run-script unit_chain
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Group Management
      if: tag IS NOT present
      script: npm run-script unit_gm
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Permission Management
      if: tag IS NOT present
      script: npm run-script unit_pm
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Role Management
      if: tag IS NOT present
      script: npm run-script unit_rm
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Quota Management
      if: tag IS NOT present
      script: npm run-script unit_qm
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Quota
      if: tag IS NOT present
      script: npm run-script unit_quota
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Abi
      if: tag IS NOT present
      script: npm run-script abi
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Admin
      if: tag IS NOT present
      script: npm run-script unit_admin
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Store
      if: tag IS NOT present
      script: npm run-script store
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Batch Tx
      if: tag IS NOT present
      script: npm run-script batch_tx
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Uint8
      if: tag IS NOT present
      script: npm run-script uint8
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit VersionManager
      if: tag IS NOT present
      script: npm run-script unit_vm

    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Node
      if: tag IS NOT present
      install:
        - cd $TRAVIS_BUILD_DIR/target/install
        - ./bin/cita create
            --nodes "127.0.0.1:4000,127.0.0.1:4001,127.0.0.1:4002"
            --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523"
        - for i in {0..2} ; do
             ./bin/cita setup test-chain/$i
             && ./bin/cita start test-chain/$i ;
          done
      script:
        - npm run-script unit_node

    - <<: *stage-contract-test-sha3-secp256k1
      name: Integrate Quota
      if: tag IS NOT present
      install:
        - cd $TRAVIS_BUILD_DIR/target/install
        - ./bin/cita create
            --nodes "127.0.0.1:4100"
            --contract_arguments "SysConfig.checkQuota=true"
            --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523"
        - ./bin/cita setup test-chain/0
        - ./bin/cita start test-chain/0
      script:
        - npm run-script integrate_quota

    - <<: *stage-contract-test-sha3-secp256k1
      name: Integrate Permission
      if: tag IS NOT present
      install:
        - cd $TRAVIS_BUILD_DIR/target/install
        - ./bin/cita create
            --nodes "127.0.0.1:4100"
            --contract_arguments "SysConfig.checkCallPermission=true"
            --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523"
        - ./bin/cita setup test-chain/0
        - ./bin/cita start test-chain/0
      script:
        - npm run-script permission

    - <<: *stage-contract-test-sha3-secp256k1
      name: Integrate AutoExec
      if: tag IS NOT present
      install:
        - cd $TRAVIS_BUILD_DIR/target/install
        - ./bin/cita create
            --nodes "127.0.0.1:4100"
            --contract_arguments "SysConfig.autoExec=true"
            --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523"
        - ./bin/cita setup test-chain/0
        - ./bin/cita start test-chain/0
      script:
        - npm run-script auto_exec

    - <<: *stage-contract-test-sha3-secp256k1
      name: Integrate Lifetime
      if: tag IS NOT present
      install:
        - cd $TRAVIS_BUILD_DIR/target/install
        - ./bin/cita create
            --nodes "127.0.0.1:4100"
            --contract_arguments "SysConfig.economicalModel=1 PriceManager.quotaPrice=1"
            --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523"
            --init_token 0x1000000
        - ./bin/cita setup test-chain/0
        - ./bin/cita start test-chain/0
      script:
        - npm run-script lifetime
before_deploy:
- ./scripts/release_cita_secp256k1_sha3.sh
deploy:
  provider: releases
  api_key:
    secure: JJiuOgi6i+SIlbyVS+LJg3XmQ3tLJ+hn5g5r7vaPoXrU3e42IHabHsgpdsuiOupUInxRmBasQVgRCpsWZ2qenev84so7BRp94QlS5IHJqV3fzutGQjztJ55dym2C5S4QzXCvfyMS+eC5HkRjm2orZXAYWPhWMGO835vPh2p+efu30onPQkqZXw0eZKVleFTd5eQbTgSdONsXX92rytNktbIXPdMfsm5bblkYk0tXi5SB2Hl9qsV3paF1sUa0VOeKZ5HA+vejz4YVHyNYDg6qSMClwoixEBEiMixQ01FcIVLsDHZ25maL3VKxkRfuk2BxPdQrQZYuAAHuOss6slxQS+xovwQbi3Zu8TsCFvS5wgtSGZeGMB0BrMxvvjsKtMYkDgobUcayxR69wfaZThWcTFAiIdiAg9Z/csd9x9MOFVGpKG0Aw0PjlmvdF1FkcASxh0JaqEZV8c+CGpyQbD8rbzLg1fdnHQFLUwiHn2jT0ehGqMA+B0mIbEE9iyKgjMepzTTjP+j+URU8mpoZdwP02tbelH3n+H3s6WKnR+W0ibroxvWHuQ5YAEOci+EsfV72XYCZEUJLr6eClOc6PoW3B1lp1mkFPSbXrImSlWfI3NWElnKZoV6l3KARirxrKZVtg5/vd8mxecmuRJ0x7G9Eze76OC7SOZLyWJCKfdFr+s8=
  file: "./docker/release/cita_secp256k1_sha3.tar.gz"
  on:
    tags: true
  skip_cleanup: 'true'

