language: generic
sudo: required
cache:
  timeout: 600
  directories:
  - "$TRAVIS_BUILD_DIR/target/debug"
  - "/opt/.cargo/git"
  - "/opt/.cargo/registry"
services:
- docker
git:
  depth: 1
stages:
- CheckShell
- Release
- IntegrateTest
before_install:
- docker pull cita/cita-build:ubuntu-18.04-20200606
jobs:
  include:
  - stage: CheckShell
    script:
    - shellcheck scripts/*.sh env.sh
  - stage: Release
    name: Release for Integrate Test
    language: node_js
    node_js:
    - 8.10.0
    cache:
      directories:
      - "$TRAVIS_BUILD_DIR/target/release-cache"
    env: HASH_ALGO=sha3hash    CRYPTO_ALGO=secp256k1
    before_script:
    - cd $TRAVIS_BUILD_DIR
    - "./scripts/replace_default_feature.sh ./ sha3hash  ${HASH_ALGO}"
    - "./scripts/replace_default_feature.sh ./ secp256k1 ${CRYPTO_ALGO}"
    script: "./env.sh make release"
    before_cache:
    - cd $TRAVIS_BUILD_DIR
    - rm -rf target/release-cache
    - cp -r  target/install /docker/releasecita_secp256k1_sha3
    - echo "ls shifou" "$(ls)"
    - mv -vf target/install target/release-cache
  - stage: IntegrateTest
    name: Unit Group
    language: node_js
    node_js: &1
    - 8.10.0
    cache: &2
      directories:
      - "$TRAVIS_BUILD_DIR/target/release-cache"
    env: HASH_ALGO=sha3hash    CRYPTO_ALGO=secp256k1
    before_install: &3
    - cd $TRAVIS_BUILD_DIR
    - rm -rf target/install
    - cp -rv target/release-cache target/install
    install: &4
    - rm -rf /opt/cita-run/test-chain
    - cd $TRAVIS_BUILD_DIR/target/install
    - ./bin/cita create --nodes "127.0.0.1:4100" --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523"
    - "./bin/cita setup test-chain/0"
    - "./bin/cita start test-chain/0"
    before_script: &5
    - cd $TRAVIS_BUILD_DIR/target/install/scripts/contracts/tests
    - travis_retry yarn install
    script: npm run-script unit_group
  - stage: IntegrateTest
    name: Unit Chain
    language: node_js
    node_js: *1
    cache: *2
    env: HASH_ALGO=sha3hash    CRYPTO_ALGO=secp256k1
    before_install: *3
    install: *4
    before_script: *5
    script: npm run-script unit_chain
before_deploy:
  - ./scripts/release_cita_secp256k1_sha3.sh
deploy:
  provider: releases
  api_key:
    secure: JJiuOgi6i+SIlbyVS+LJg3XmQ3tLJ+hn5g5r7vaPoXrU3e42IHabHsgpdsuiOupUInxRmBasQVgRCpsWZ2qenev84so7BRp94QlS5IHJqV3fzutGQjztJ55dym2C5S4QzXCvfyMS+eC5HkRjm2orZXAYWPhWMGO835vPh2p+efu30onPQkqZXw0eZKVleFTd5eQbTgSdONsXX92rytNktbIXPdMfsm5bblkYk0tXi5SB2Hl9qsV3paF1sUa0VOeKZ5HA+vejz4YVHyNYDg6qSMClwoixEBEiMixQ01FcIVLsDHZ25maL3VKxkRfuk2BxPdQrQZYuAAHuOss6slxQS+xovwQbi3Zu8TsCFvS5wgtSGZeGMB0BrMxvvjsKtMYkDgobUcayxR69wfaZThWcTFAiIdiAg9Z/csd9x9MOFVGpKG0Aw0PjlmvdF1FkcASxh0JaqEZV8c+CGpyQbD8rbzLg1fdnHQFLUwiHn2jT0ehGqMA+B0mIbEE9iyKgjMepzTTjP+j+URU8mpoZdwP02tbelH3n+H3s6WKnR+W0ibroxvWHuQ5YAEOci+EsfV72XYCZEUJLr6eClOc6PoW3B1lp1mkFPSbXrImSlWfI3NWElnKZoV6l3KARirxrKZVtg5/vd8mxecmuRJ0x7G9Eze76OC7SOZLyWJCKfdFr+s8=
  file: "./docker/release/cita_secp256k1_sha3.tar.gz"
  on:
    tags: true
  skip_cleanup: 'true'
